version: '3.8'

services:
  
  # Web App Service
  web-app:
    build: 
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "8080:5000"
    depends_on:
      - mlapi
    environment:
      - MONGO_URI=mongodb+srv://lgl1876523678:1017@cluster0.k8xwe.mongodb.net/?retryWrites=true&w=majority
    networks:
      - app-network
    restart: unless-stopped
  
  # Machine Learning Client Service
  mlapi:
    build: 
      context: ./machine-learning-client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: ml-client
    environment:
      - MONGO_URI=mongodb+srv://lgl1876523678:1017@cluster0.k8xwe.mongodb.net/?retryWrites=true&w=majority
    networks:
      - app-network
    restart: unless-stopped
    # restart: "no"


networks:
  app-network:
    driver: bridge