name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # repeat same job for each subsystem in the following subdirectories
        subdir: [web-app, machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # update version(s) as needed
      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pylint black
      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        # Ignoring specific errors and adding more verbose output
        run: |
          cd ${{ matrix.subdir }}
          pylint --disable=C0111,C0103,E0401,C0303,C0301,E1101,W0601,R1705,C0413,C0304,W0718,W0612,W0611,W0621,C1803,W0613,W1203,C0415,W1309,R0914,R0913,R0917 **/*.py ||