name: ML Client Tests

on:
  push:
    paths:
      - "machine-learning-client/**"
      - ".github/workflows/ml-client-test.yml"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: machine-learning-client

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
